# Configuration file for the ML Testbed Platform

# Device to use for training (cuda or cpu)
device: "cuda"

# Dataset configuration
dataset:
  name: "CIFAR100" # Available datasets: MNIST, CIFAR10, CIFAR100
  batch_size: 64

# List of transformations to apply to the data
# Available transformations: ToTensor, Normalize, Resize
# Transformations can be configured with parameters:
#   Normalize: mean: 0.1307
#   std: 0.3081
transformations:
  - name: "ToTensor"
  - name: "Normalize"
    mean: 0.1307
    std: 0.3081

# Learning rate for the optimizer
learning_rate: 0.001

# Number of epochs to train for
epochs: 5

# Loss function to use for training
loss: "CrossEntropyLoss" # Possible values: MSELoss, MAELoss, CrossEntropyLoss

# Metrics to track during training
metrics:
  - name: "Accuracy"
  - name: "F1"
  - name: "ConfusionMatrix"
  - name: "Precision"
  - name: "Recall"
  - name: "AUC"
  - name: "ROC"
  - name: "AveragePrecision"

# Example configuration:
# To train on CPU with a learning rate of 0.01 for 10 epochs, use the following configuration:
# device: "cpu"
# learning_rate: 0.01
# epochs: 10