device: "cpu"
transformations:
  - name: "ToTensor"
learning_rate: 0.001
epochs: 1
dataset:
  name: "mnist"
  batch_size: 32
metrics:
  - name: "Accuracy"
optimizer:
  name: "SGD"
  config:
    lr: 0.01
    momentum: 0.9
wandb:
  enabled: False